"use strict";
class ShapeEvolution {
  constructor(target,result,heatmap,onUpdate){this.targetCanvas=target;this.canvas=result;this.heatCanvas=heatmap;this.tctx=target.getContext("2d",{willReadFrequently:true});this.ctx=result.getContext("2d");this.hctx=heatmap.getContext("2d");this.work=document.createElement("canvas");this.wctx=this.work.getContext("2d",{willReadFrequently:true});this.onUpdate=onUpdate;this.shapes=[];this.running=false;this.attempts=0;this.accepted=0;this.loss=Infinity;this.stagnant=0;this.stage=0;this.sigma=.18;this.targetImage=null;this.targetData=null;this.edgeTarget=null;this.errorMap=null;this.lastPaint=0;this.presets={quick:{max:120,lambda:4,stages:[48,80,120]},balanced:{max:250,lambda:6,stages:[48,80,120,180]},fine:{max:450,lambda:8,stages:[48,80,120,180,240]}};this.config=this.presets.balanced}
  async load(src){const img=await loadImage(src);this.targetImage=img;this.paintTarget();this.reset()}
  paintTarget(){const c=this.targetCanvas,x=this.tctx,ratio=this.targetImage.width/this.targetImage.height;c.width=480;c.height=Math.round(480/ratio);this.canvas.width=this.heatCanvas.width=c.width;this.canvas.height=this.heatCanvas.height=c.height;x.fillStyle="#fff";x.fillRect(0,0,c.width,c.height);x.drawImage(this.targetImage,0,0,c.width,c.height)}
  setPreset(name){this.config=this.presets[name]||this.presets.balanced;this.reset()}
  reset(){this.pause();this.shapes=[];this.attempts=this.accepted=this.stage=this.stagnant=0;this.sigma=.18;this.prepareStage();this.loss=this.evaluate(this.shapes,true);this.renderVisible();this.update("ready")}
  prepareStage(){const width=this.config.stages[this.stage],height=Math.max(1,Math.round(width*this.targetCanvas.height/this.targetCanvas.width));this.work.width=width;this.work.height=height;const tc=document.createElement("canvas"),tx=tc.getContext("2d",{willReadFrequently:true});tc.width=width;tc.height=height;tx.drawImage(this.targetCanvas,0,0,width,height);this.targetData=tx.getImageData(0,0,width,height).data;this.edgeTarget=this.edges(this.targetData,width,height);this.loss=Infinity}
  start(){if(this.shapes.length>=this.config.max)return;this.running=true;this.loop()}
  pause(){this.running=false}
  loop(){if(!this.running)return;const start=performance.now(),budget=[4,7,11,16,24][window.evolutionSpeed-1]||11;while(performance.now()-start<budget&&this.running)this.generation();if(performance.now()-this.lastPaint>90){this.renderVisible();this.update("running");this.lastPaint=performance.now()}requestAnimationFrame(()=>this.loop())}
  generation(){const trials=[];for(let i=0;i<this.config.lambda;i++){const child=this.cloneShapes(this.shapes);this.mutateGenome(child);const loss=this.evaluate(child,false);trials.push({child,loss})}trials.sort((a,b)=>a.loss-b.loss);this.attempts+=trials.length;if(trials[0].loss+1e-7<this.loss){this.shapes=trials[0].child;this.loss=trials[0].loss;this.accepted++;this.stagnant=0;this.sigma=Math.min(.28,this.sigma*1.015)}else{this.stagnant++;this.sigma=Math.max(.025,this.sigma*.998)}if(this.attempts%180===0)this.rebuildErrorMap();const promotion=this.stagnant>180+this.stage*80||this.shapes.length>=this.stageShapeGoal();if(promotion&&this.stage<this.config.stages.length-1){this.stage++;this.stagnant=0;this.prepareStage();this.loss=this.evaluate(this.shapes,true)}if(this.shapes.length>=this.config.max&&this.stagnant>500){this.pause();this.renderVisible();this.update("finished")}}
  stageShapeGoal(){return Math.round(this.config.max*(this.stage+1)/this.config.stages.length)}
  mutateGenome(list){const canAdd=list.length<this.config.max,roll=Math.random();if(canAdd&&(list.length<8||roll<.44)){list.push(this.newShape())}else if(list.length&&roll<.84){const index=this.pickShape(list),s=list[index];this.mutateShape(s);if(Math.random()<.12&&index>0){list.splice(index,1);list.splice(Math.max(0,index+(Math.random()<.5?-1:1)),0,s)}}else if(list.length>12&&roll<.94){list.splice(this.pickShape(list),1)}else if(canAdd&&list.length){const source=list[this.pickShape(list)],copy={...source};this.mutateShape(copy,.45);copy.a*=.72;list.push(copy)}}
  newShape(){const p=this.pickErrorPoint(),target=this.sampleTarget(p.x,p.y),large=this.stage<2,kind=Math.random()<.72?"triangle":"ellipse",radius=(large?.12:.055)*(0.45+Math.random());return kind==="triangle"?{kind,x:p.x,y:p.y,x1:p.x+(Math.random()-.5)*radius,y1:p.y+(Math.random()-.5)*radius,x2:p.x+(Math.random()-.5)*radius,y2:p.y+(Math.random()-.5)*radius,x3:p.x+(Math.random()-.5)*radius,y3:p.y+(Math.random()-.5)*radius,r:target[0],g:target[1],b:target[2],a:.12+Math.random()*.34}:{kind,x:p.x,y:p.y,rx:radius,ry:radius*(.4+Math.random()),rot:Math.random()*Math.PI,r:target[0],g:target[1],b:target[2],a:.1+Math.random()*.3}}
  mutateShape(s,factor=1){const m=this.sigma*factor,p=this.pickErrorPoint();if(Math.random()<.18){s.x=lerp(s.x,p.x,.2+Math.random()*.35);s.y=lerp(s.y,p.y,.2+Math.random()*.35)}const n=()=>gaussian()*m;if(s.kind==="triangle"){for(const k of ["x1","x2","x3"])s[k]=clamp(s[k]+n());for(const k of ["y1","y2","y3"])s[k]=clamp(s[k]+n())}else{s.x=clamp(s.x+n());s.y=clamp(s.y+n());s.rx=clamp(s.rx+n()*.45,.004,.35);s.ry=clamp(s.ry+n()*.45,.004,.35);s.rot+=n()*3}s.r=clamp255(s.r+n()*170);s.g=clamp255(s.g+n()*170);s.b=clamp255(s.b+n()*170);s.a=clamp(s.a+n()*.7,.025,.72)}
  pickShape(list){let total=0,weights=list.map((s,i)=>total+=(.3+s.a)*(i/list.length+.35));let r=Math.random()*total;for(let i=0;i<weights.length;i++)if(r<weights[i])return i;return list.length-1}
  pickErrorPoint(){if(!this.errorMap||Math.random()<.18)return{x:Math.random(),y:Math.random()};let total=this.errorMap.total,r=Math.random()*total;for(let i=0;i<this.errorMap.values.length;i++){r-=this.errorMap.values[i];if(r<=0)return{x:(i%this.work.width+.5)/this.work.width,y:(Math.floor(i/this.work.width)+.5)/this.work.height}}return{x:Math.random(),y:Math.random()}}
  sampleTarget(x,y){const ix=Math.min(this.work.width-1,Math.floor(x*this.work.width)),iy=Math.min(this.work.height-1,Math.floor(y*this.work.height)),i=(iy*this.work.width+ix)*4;return[this.targetData[i],this.targetData[i+1],this.targetData[i+2]]}
  evaluate(shapes,makeMap){this.draw(this.wctx,this.work.width,this.work.height,shapes);const data=this.wctx.getImageData(0,0,this.work.width,this.work.height).data,edge=this.edges(data,this.work.width,this.work.height);let colour=0,edgeLoss=0;const residual=makeMap?new Float32Array(this.work.width*this.work.height):null;for(let p=0,i=0;i<data.length;i+=4,p++){const dr=(data[i]-this.targetData[i])/255,dg=(data[i+1]-this.targetData[i+1])/255,db=(data[i+2]-this.targetData[i+2])/255,e=Math.sqrt(dr*dr+dg*dg+db*db);colour+=e;edgeLoss+=Math.abs(edge[p]-this.edgeTarget[p]);if(residual)residual[p]=.01+e*e+Math.abs(edge[p]-this.edgeTarget[p])*.35}const pixels=this.work.width*this.work.height;if(residual){let total=0;for(const v of residual)total+=v;this.errorMap={values:residual,total}}return colour/pixels*.82+edgeLoss/pixels*.18+shapes.length*.000003}
  rebuildErrorMap(){this.evaluate(this.shapes,true)}
  edges(data,w,h){const out=new Float32Array(w*h);for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=(y*w+x)*4,l=i-4,r=i+4,u=i-w*4,d=i+w*4;const lum=j=>(data[j]*.2126+data[j+1]*.7152+data[j+2]*.0722)/255;out[y*w+x]=Math.min(1,Math.abs(lum(r)-lum(l))+Math.abs(lum(d)-lum(u)))}return out}
  draw(ctx,w,h,shapes){ctx.globalAlpha=1;ctx.fillStyle="#e5e1d6";ctx.fillRect(0,0,w,h);for(const s of shapes){ctx.globalAlpha=s.a;ctx.fillStyle=`rgb(${s.r|0} ${s.g|0} ${s.b|0})`;ctx.beginPath();if(s.kind==="triangle"){ctx.moveTo(s.x1*w,s.y1*h);ctx.lineTo(s.x2*w,s.y2*h);ctx.lineTo(s.x3*w,s.y3*h);ctx.closePath()}else{ctx.ellipse(s.x*w,s.y*h,s.rx*w,s.ry*h,s.rot,0,Math.PI*2)}ctx.fill()}ctx.globalAlpha=1}
  renderVisible(){this.draw(this.ctx,this.canvas.width,this.canvas.height,this.shapes);this.renderHeatmap()}
  renderHeatmap(){if(!this.errorMap)return;const small=document.createElement("canvas");small.width=this.work.width;small.height=this.work.height;const sx=small.getContext("2d"),img=sx.createImageData(this.work.width,this.work.height);let max=.001;for(const v of this.errorMap.values)max=Math.max(max,v);for(let i=0;i<this.errorMap.values.length;i++){const v=Math.min(1,this.errorMap.values[i]/max*2.2),j=i*4;img.data[j]=255;img.data[j+1]=Math.round(80*(1-v));img.data[j+2]=20;img.data[j+3]=Math.round(v*230)}sx.putImageData(img,0,0);this.hctx.clearRect(0,0,this.heatCanvas.width,this.heatCanvas.height);this.hctx.imageSmoothingEnabled=true;this.hctx.drawImage(small,0,0,this.heatCanvas.width,this.heatCanvas.height)}
  cloneShapes(s){return s.map(x=>({...x}))}
  similarity(){return Math.max(0,Math.min(99.99,(1-this.loss/1.3)*100))}
  update(state){this.onUpdate({state,shapes:this.shapes.length,attempts:this.attempts,similarity:this.similarity(),stage:this.stage,stages:this.config.stages.length,max:this.config.max,accepted:this.accepted})}
  exportJSON(){return JSON.stringify({format:"jenga-vector-evolution",version:2,width:this.canvas.width,height:this.canvas.height,shapes:this.shapes},null,2)}
}
const $=id=>document.getElementById(id),target=$("target"),result=$("result"),heatmap=$("heatmap"),start=$("start"),reset=$("reset"),quality=$("quality"),speed=$("speed"),upload=$("upload"),uploadButton=$("uploadButton"),toggleHeatmap=$("toggleHeatmap"),png=$("downloadPng"),gifButton=$("downloadGif"),json=$("downloadJson");window.evolutionSpeed=+speed.value;
const phases=["Structure","Composition","Features","Detail","Polish"];
const evolution=new ShapeEvolution(target,result,heatmap,s=>{$("shapeCount").textContent=s.shapes;$ ("attempts").textContent=s.attempts.toLocaleString();$("similarity").textContent=s.similarity.toFixed(2)+"%";$("progressBar").style.width=Math.min(100,s.shapes/s.max*100)+"%";$("stageText").textContent=phases[s.stage];png.disabled=gifButton.disabled=json.disabled=s.shapes===0;if(s.state==="ready"){setStatus("Ready to evolve","Ready. Broad shapes establish the composition first.");start.innerHTML="<span>▶</span> Start evolving"}else if(s.state==="running"){setStatus("Evolution in progress",`Testing targeted mutations; ${s.accepted.toLocaleString()} improvements have survived.`);start.textContent="Pause"}else if(s.state==="finished"){setStatus("Evolution complete","The shape budget is complete. Download the artwork or begin another run.");start.textContent="Finished"}});
function setStatus(a,b){$("statusTitle").textContent=a;$("statusText").textContent=b}function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}function loadImage(src){return new Promise((resolve,reject)=>{const i=new Image;i.onload=()=>resolve(i);i.onerror=reject;i.src=src})}function clamp(v,min=0,max=1){return Math.max(min,Math.min(max,v))}function clamp255(v){return clamp(v,0,255)}function lerp(a,b,t){return a+(b-a)*t}function gaussian(){return(Math.random()+Math.random()+Math.random()+Math.random()-2)/2}
async function exportBuildGif(){if(!evolution.shapes.length||typeof GIF!=="function")return;const wasRunning=evolution.running;evolution.pause();gifButton.disabled=true;const oldText=gifButton.textContent,w=320,h=Math.round(320*result.height/result.width),canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");canvas.width=w;canvas.height=h;const encoder=new GIF({workers:2,quality:10,width:w,height:h,workerScript:"js/gif.worker.js"}),count=evolution.shapes.length,step=Math.max(1,Math.ceil(count/90));for(let n=0;n<=count;n+=step){evolution.draw(ctx,w,h,evolution.shapes.slice(0,n));encoder.addFrame(ctx,{copy:true,delay:n===0?500:65})}if(count%step){evolution.draw(ctx,w,h,evolution.shapes);encoder.addFrame(ctx,{copy:true,delay:1200})}encoder.on("progress",p=>{gifButton.textContent=`Encoding ${Math.round(p*100)}%`});encoder.on("finished",blob=>{download(blob,"evolved-mona-lisa-build.gif");gifButton.textContent=oldText;gifButton.disabled=false;setStatus("GIF downloaded","The animation shows the final vector artwork assembling shape by shape.");if(wasRunning)evolution.start()});encoder.render()}
start.addEventListener("click",()=>{if(evolution.running){evolution.pause();start.innerHTML="<span>▶</span> Continue";setStatus("Evolution paused","Continue whenever you are ready.")}else evolution.start()});reset.addEventListener("click",()=>evolution.reset());quality.addEventListener("change",()=>evolution.setPreset(quality.value));speed.addEventListener("input",()=>window.evolutionSpeed=+speed.value);uploadButton.addEventListener("click",()=>upload.click());upload.addEventListener("change",async()=>{const file=upload.files[0];if(file){const url=URL.createObjectURL(file);await evolution.load(url);URL.revokeObjectURL(url)}});toggleHeatmap.addEventListener("click",()=>{const visible=heatmap.classList.toggle("visible");toggleHeatmap.textContent=visible?"Hide error map":"Show error map"});png.addEventListener("click",()=>result.toBlob(b=>download(b,"evolved-mona-lisa.png"),"image/png"));gifButton.addEventListener("click",exportBuildGif);json.addEventListener("click",()=>download(new Blob([evolution.exportJSON()],{type:"application/json"}),"evolved-mona-lisa.json"));
evolution.load("images/mona-lisa.jpg").catch(()=>setStatus("Image unavailable","Check that images/mona-lisa.jpg was uploaded with the page."));
